---
name: build
on:
  - push
jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: extractions/setup-just@v2
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - run: just build
